import { defaultRange, getSnapshot, previousPeriod, type CampaignRow, type Period, type Snapshot } from "@/lib/dashboard";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const eur = new Intl.NumberFormat("pt-PT", { style:"currency", currency:"EUR", maximumFractionDigits:0 });
const eur2 = new Intl.NumberFormat("pt-PT", { style:"currency", currency:"EUR", minimumFractionDigits:2, maximumFractionDigits:2 });
const int = new Intl.NumberFormat("pt-PT", { maximumFractionDigits:0 });
const one = new Intl.NumberFormat("pt-PT", { minimumFractionDigits:1, maximumFractionDigits:1 });
const pctDelta=(a:number,b:number)=>b===0?(a===0?0:null):((a-b)/b)*100;
const safe=(v?:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v||"")?v:undefined;

function Delta({a,b,inverse=false}:{a:number;b:number;inverse?:boolean}){const d=pctDelta(a,b);if(d===null)return <span className="delta neutral">sem base</span>;const good=inverse?d<0:d>0,bad=inverse?d>0:d<0;return <span className={`delta ${good?"good":bad?"bad":"neutral"}`}>{d>0?"+":""}{one.format(d)}% <em>vs anterior</em></span>}
function Card({label,value,note,a,b,inverse=false,dark=false}:{label:string;value:string;note:string;a:number;b:number;inverse?:boolean;dark?:boolean}){return <article className={`kpi ${dark?"dark":""}`}><span>{label}</span><strong>{value}</strong><p>{note}</p><Delta a={a} b={b} inverse={inverse}/></article>}
function PanelTitle({kicker,title,right}:{kicker:string;title:string;right?:React.ReactNode}){return <div className="panel-head"><div><span>{kicker}</span><h2>{title}</h2></div>{right}</div>}

function Spend({c,p}:{c:Snapshot;p:Snapshot}){const total=c.totalSpend||1,mp=c.metaSpend/total*100,gp=c.googleSpend/total*100;return <section className="panel"><PanelTitle kicker="Aquisição paga" title="Investimento em Ads" right={<div className="mini-total"><span>Total</span><strong>{eur.format(c.totalSpend)}</strong></div>}/><div className="spend-cards"><div><b className="dot meta"/><span>Meta Ads</span><strong>{eur.format(c.metaSpend)}</strong><Delta a={c.metaSpend} b={p.metaSpend} inverse/><small>{one.format(mp)}% do investimento</small></div><div><b className="dot google"/><span>Google Ads</span><strong>{eur.format(c.googleSpend)}</strong><Delta a={c.googleSpend} b={p.googleSpend} inverse/><small>{one.format(gp)}% do investimento</small></div></div><div className="split"><i style={{width:`${mp}%`}}/><b style={{width:`${gp}%`}}/></div></section>}

function Sources({c,p}:{c:Snapshot;p:Snapshot}){const entries=Object.entries(c.sources) as [keyof Snapshot["sources"],{orders:number;revenue:number}][],max=Math.max(1,...entries.map(([,x])=>x.orders));return <section className="panel"><PanelTitle kicker="Atribuição Shopify" title="De onde vieram as encomendas?" right={<span className="pill">Último clique · sem duplicação</span>}/><div className="source-wrap"><div className="sources">{entries.map(([name,x])=>{const d=pctDelta(x.orders,p.sources[name]?.orders||0);return <div className="source" key={name}><div><strong>{name}</strong><small>{x.orders} encomendas · {eur.format(x.revenue)}</small></div><div className="track"><i style={{width:`${Math.max(x.orders/max*100,x.orders?5:0)}%`}}/></div><b className={d===null||d===0?"neutral":d>0?"good":"bad"}>{d===null?"novo":`${d>0?"+":""}${one.format(d)}%`}</b></div>})}</div><aside><span>Encomendas pagas</span><strong>{int.format(c.orders)}</strong><small>{eur.format(c.revenue)} receita</small><hr/><span>Ticket médio</span><b>{eur2.format(c.aov)}</b></aside></div></section>}

function Leakage({c,p}:{c:Snapshot;p:Snapshot}){const risk=c.unpaidValue+c.abandonedValue,prev=p.unpaidValue+p.abandonedValue;return <section className="panel leak"><PanelTitle kicker="Fugas de receita" title="Onde estamos a perder conversão?" right={<div className="risk"><span>Valor potencial em risco</span><strong>{eur.format(risk)}</strong><Delta a={risk} b={prev} inverse/></div>}/><div className="leak-grid"><article><i>01</i><div><span>Encomendas não pagas</span><strong>{c.unpaidOrders}</strong><small>{eur.format(c.unpaidValue)} por receber</small></div><Delta a={c.unpaidOrders} b={p.unpaidOrders} inverse/></article><article className="danger"><i>02</i><div><span>Carrinhos / checkout abandonados</span><strong>{c.abandonedCheckouts}</strong><small>{eur.format(c.abandonedValue)} potencial não convertido</small></div><Delta a={c.abandonedValue} b={p.abandonedValue} inverse/></article><article className="recovered"><i>03</i><div><span>Checkouts recuperados</span><strong>{c.recoveredCheckouts}</strong><small>recuperados no período</small></div><Delta a={c.recoveredCheckouts} b={p.recoveredCheckouts}/></article></div><p className="method">“Valor potencial não convertido” não é perda contabilística. O Shopify identifica o abandono quando o cliente entra no checkout e deixa dados suficientes para o registo.</p></section>}

function Trend({c}:{c:Snapshot}){const mr=Math.max(1,...c.daily.map(x=>x.revenue)),ms=Math.max(1,...c.daily.map(x=>x.metaSpend+x.googleSpend));return <section className="panel"><PanelTitle kicker="Evolução diária" title="Receita vs. investimento" right={<div className="legend"><span><i/>Receita</span><span><b/>Ads</span></div>}/><div className="chart">{c.daily.map(x=>{const spend=x.metaSpend+x.googleSpend;return <div className="day" key={x.date} title={`${eur2.format(x.revenue)} receita · ${eur2.format(spend)} Ads`}><div><i style={{height:`${Math.max(x.revenue/mr*100,x.revenue?4:0)}%`}}/><b style={{height:`${Math.max(spend/ms*100,spend?4:0)}%`}}/></div><small>{new Date(`${x.date}T12:00:00Z`).toLocaleDateString("pt-PT",{day:"2-digit",month:"short"}).replace(".","")}</small></div>})}</div></section>}

function Campaigns({rows}:{rows:CampaignRow[]}){return <section className="panel"><PanelTitle kicker="Diagnóstico de media" title="Campanhas com maior investimento" right={<span className="pill">Conversões das plataformas</span>}/>{rows.length?<div className="table"><table><thead><tr><th>Plataforma</th><th>Grupo</th><th>Campanha</th><th>Invest.</th><th>Conv.</th><th>Valor</th><th>ROAS</th><th>CPA</th><th>CTR</th><th>CPC</th></tr></thead><tbody>{rows.slice(0,14).map(r=><tr key={`${r.platform}-${r.group}-${r.campaign}`}><td><span className={`badge ${r.platform.toLowerCase()}`}>{r.platform}</span></td><td>{r.group}</td><td className="name">{r.campaign}</td><td>{eur2.format(r.spend)}</td><td>{one.format(r.conversions)}</td><td>{eur.format(r.conversionValue)}</td><td className={r.roas!==null&&r.roas>=4?"positive":r.roas!==null&&r.roas<2?"negative":""}>{r.roas===null?"—":`${one.format(r.roas)}×`}</td><td>{r.cpa===null?"—":eur2.format(r.cpa)}</td><td>{r.ctr===null?"—":`${one.format(r.ctr)}%`}</td><td>{r.cpc===null?"—":eur2.format(r.cpc)}</td></tr>)}</tbody></table></div>:<div className="empty">Sem dados de campanha neste período.</div>}</section>}

function Picker({r}:{r:Period}){return <form className="picker"><label>De<input type="date" name="from" defaultValue={r.from}/></label><label>Até<input type="date" name="to" defaultValue={r.to}/></label><button>Atualizar</button></form>}

export default async function Home({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const q=await searchParams,f=defaultRange(7),from=safe(typeof q.from==="string"?q.from:undefined)||f.from,to=safe(typeof q.to==="string"?q.to:undefined)||f.to,r=from<=to?{from,to}:f,pr=previousPeriod(r),[c,p]=await Promise.all([getSnapshot(r),getSnapshot(pr)]);return <main className="shell"><header><div className="brand"><span>LO</span><div><strong>Loja do Ouro</strong><small>Performance Control Center</small></div></div><Picker r={r}/></header><section className="hero"><div><span>VISÃO EXECUTIVA</span><h1>O que aconteceu no e-commerce?</h1><p>{new Date(`${r.from}T12:00:00Z`).toLocaleDateString("pt-PT")} — {new Date(`${r.to}T12:00:00Z`).toLocaleDateString("pt-PT")} · comparação automática com o período anterior.</p></div><aside><i/><div><span>Atualizado</span><strong>{new Date(c.generatedAt).toLocaleString("pt-PT",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Lisbon"})}</strong></div></aside></section>{c.warnings.length>0&&<div className="warning"><strong>Atenção à cobertura de dados</strong><span>{c.warnings.join(" · ")}</span></div>}<section className="kpis"><Card label="Receita paga" value={eur.format(c.revenue)} note={`${c.orders} encomendas pagas`} a={c.revenue} b={p.revenue} dark/><Card label="Encomendas" value={int.format(c.orders)} note="pagas e não canceladas" a={c.orders} b={p.orders}/><Card label="Ticket médio" value={eur2.format(c.aov)} note="receita / encomenda paga" a={c.aov} b={p.aov}/><Card label="Investimento total Ads" value={eur.format(c.totalSpend)} note={`Meta ${eur.format(c.metaSpend)} · Google ${eur.format(c.googleSpend)}`} a={c.totalSpend} b={p.totalSpend} inverse/><Card label="ROAS blended" value={c.blendedRoas===null?"—":`${one.format(c.blendedRoas)}×`} note="receita Shopify / Ads totais" a={c.blendedRoas||0} b={p.blendedRoas||0}/></section><div className="cols"><Spend c={c} p={p}/><Sources c={c} p={p}/></div><Leakage c={c} p={p}/><Trend c={c}/><Campaigns rows={c.campaigns}/><footer><div><strong>Loja do Ouro · Dashboard v2</strong><span>Shopify = fonte de verdade de encomendas e receita · Windsor.ai = investimento e performance de media.</span></div><span>Atribuição principal: último clique registado pelo Shopify.</span></footer></main>}
