import { defaultRange, getSnapshot, previousPeriod, type CampaignRow, type Period, type Snapshot } from "@/lib/dashboard";
import { getExecutivePulse, getIntelligence, type IntelligenceSnapshot, type ExecutiveWindowSummary } from "@/lib/business-intelligence";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const eur = new Intl.NumberFormat("pt-PT", { style:"currency", currency:"EUR", maximumFractionDigits:0 });
const eur2 = new Intl.NumberFormat("pt-PT", { style:"currency", currency:"EUR", minimumFractionDigits:2, maximumFractionDigits:2 });
const int = new Intl.NumberFormat("pt-PT", { maximumFractionDigits:0 });
const one = new Intl.NumberFormat("pt-PT", { minimumFractionDigits:1, maximumFractionDigits:1 });
const pctDelta=(a:number,b:number)=>b===0?(a===0?0:null):((a-b)/b)*100;
const safe=(v?:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v||"")?v:undefined;
const pct=(v:number)=>`${one.format(v*100)}%`;
const date=(v:string)=>new Date(`${v}T12:00:00Z`).toLocaleDateString("pt-PT",{day:"2-digit",month:"short",year:"numeric"}).replace(".","");

function Delta({a,b,inverse=false,compact=false}:{a:number;b:number;inverse?:boolean;compact?:boolean}){const d=pctDelta(a,b);if(d===null)return <span className="delta neutral">sem base</span>;const good=inverse?d<0:d>0,bad=inverse?d>0:d<0;return <span className={`delta ${good?"good":bad?"bad":"neutral"}`}>{d>0?"+":""}{one.format(d)}%{!compact&&<em> vs anterior</em>}</span>}
function Card({label,value,note,a,b,inverse=false,dark=false}:{label:string;value:string;note:string;a:number;b:number;inverse?:boolean;dark?:boolean}){return <article className={`kpi ${dark?"dark":""}`}><span>{label}</span><strong>{value}</strong><p>{note}</p><Delta a={a} b={b} inverse={inverse}/></article>}
function PanelTitle({kicker,title,right}:{kicker:string;title:string;right?:React.ReactNode}){return <div className="panel-head"><div><span>{kicker}</span><h2>{title}</h2></div>{right}</div>}

function Picker({r}:{r:Period}){return <form className="picker"><label>De<input type="date" name="from" defaultValue={r.from}/></label><label>Até<input type="date" name="to" defaultValue={r.to}/></label><button>Atualizar</button></form>}

function Pulse({rows}:{rows:ExecutiveWindowSummary[]}){return <section className="pulse-grid">{rows.map(x=><article className="pulse" key={x.key}><div className="pulse-head"><div><span>{x.label}</span><small>{date(x.range.from)}{x.range.from!==x.range.to?` — ${date(x.range.to)}`:""}</small></div><Delta a={x.metrics.revenue.current} b={x.metrics.revenue.previous} compact/></div><strong>{eur.format(x.metrics.revenue.current)}</strong><div className="pulse-metrics"><span><b>{int.format(x.metrics.orders.current)}</b> encomendas</span><span><b>{eur.format(x.metrics.adSpend.current)}</b> Ads</span><span><b>{one.format(x.metrics.blendedRoas.current)}×</b> ROAS</span><span><b>{int.format(x.metrics.sessions.current)}</b> sessões</span></div><div className="pulse-email"><span>Klaviyo</span><b>{eur.format(x.metrics.emailRevenue.current)}</b><small>{int.format(x.metrics.emailConversions.current)} conversões atribuídas</small></div></article>)}</section>}

function Spend({c,p}:{c:Snapshot;p:Snapshot}){const total=c.totalSpend||1,mp=c.metaSpend/total*100,gp=c.googleSpend/total*100;return <section className="panel"><PanelTitle kicker="Aquisição paga" title="Investimento em Ads" right={<div className="mini-total"><span>Total</span><strong>{eur.format(c.totalSpend)}</strong></div>}/><div className="spend-cards"><div><b className="dot meta"/><span>Meta Ads</span><strong>{eur.format(c.metaSpend)}</strong><Delta a={c.metaSpend} b={p.metaSpend} inverse/><small>{one.format(mp)}% do investimento</small></div><div><b className="dot google"/><span>Google Ads</span><strong>{eur.format(c.googleSpend)}</strong><Delta a={c.googleSpend} b={p.googleSpend} inverse/><small>{one.format(gp)}% do investimento</small></div></div><div className="split"><i style={{width:`${mp}%`}}/><b style={{width:`${gp}%`}}/></div></section>}

function Financial({c,p}:{c:Snapshot;p:Snapshot}){return <section className="panel"><PanelTitle kicker="Economia unitária" title="Rentabilidade comercial" right={<span className="pill">custos Shopify registados</span>}/><div className="finance-grid"><div><span>Margem bruta</span><strong>{c.grossMarginPct===null?"—":`${one.format(c.grossMarginPct)}%`}</strong><small>{eur.format(c.grossProfit)} contribuição bruta</small></div><div><span>COGS registado</span><strong>{eur.format(c.cogs)}</strong><small>custo dos artigos vendidos</small></div><div><span>Marketing / receita</span><strong>{c.marketingCostRatio===null?"—":`${one.format(c.marketingCostRatio)}%`}</strong><small>{eur.format(c.totalSpend)} investimento</small></div><div><span>Descontos</span><strong>{eur.format(c.discounts)}</strong><small>em encomendas pagas</small></div><div><span>Reembolsos</span><strong>{eur.format(c.refunds)}</strong><small>registados no período</small></div><div><span>Clientes novos / recorrentes</span><strong>{c.newCustomerOrders} / {c.returningCustomerOrders}</strong><small>encomendas pagas</small></div></div></section>}

function Sources({c,p}:{c:Snapshot;p:Snapshot}){const entries=Object.entries(c.sources) as [string,{orders:number;revenue:number}][],max=Math.max(1,...entries.map(([,x])=>x.orders));return <section className="panel"><PanelTitle kicker="Atribuição Shopify" title="De onde vieram as encomendas?" right={<span className="pill">última visita · sem duplicação</span>}/><div className="source-wrap"><div className="sources">{entries.map(([name,x])=>{const previousOrders=p.sources[name as keyof Snapshot["sources"]]?.orders||0,d=pctDelta(x.orders,previousOrders);return <div className="source" key={name}><div><strong>{name}</strong><small>{x.orders} encomendas · {eur.format(x.revenue)}</small></div><div className="track"><i style={{width:`${Math.max(x.orders/max*100,x.orders?5:0)}%`}}/></div><b className={d===null||d===0?"neutral":d>0?"good":"bad"}>{d===null?"novo":`${d>0?"+":""}${one.format(d)}%`}</b></div>})}</div><aside><span>Encomendas pagas</span><strong>{int.format(c.orders)}</strong><small>{eur.format(c.revenue)} receita</small><hr/><span>Ticket médio</span><b>{eur2.format(c.aov)}</b></aside></div></section>}

function Funnel({i}:{i:IntelligenceSnapshot}){const g=i.ga4;const stages=[{n:"Sessões",v:g.sessions},{n:"Vistas produto",v:g.productViews},{n:"Add to cart",v:g.addToCarts},{n:"Checkout",v:g.checkouts},{n:"Compra GA4",v:g.purchases}],max=Math.max(1,...stages.map(x=>x.v));return <section className="panel"><PanelTitle kicker="GA4" title="Funil digital e comportamento" right={<span className="pill">taxa de engagement {pct(g.engagementRate)}</span>}/><div className="funnel">{stages.map((x,idx)=><div className="funnel-step" key={x.n}><div><span>{x.n}</span><strong>{int.format(x.v)}</strong>{idx>0&&<small>{stages[idx-1].v?`${one.format(x.v/stages[idx-1].v*100)}% da etapa anterior`:"—"}</small>}</div><i style={{width:`${Math.max(8,x.v/max*100)}%`}}/></div>)}</div><div className="funnel-foot"><span><b>{int.format(g.activeUsers)}</b> utilizadores ativos</span><span><b>{int.format(g.firstTimePurchasers)}</b> primeiros compradores</span><span><b>{eur.format(g.purchaseRevenue)}</b> purchase revenue GA4</span></div></section>}

function Leakage({c,p}:{c:Snapshot;p:Snapshot}){const risk=c.unpaidValue+c.abandonedValue,prev=p.unpaidValue+p.abandonedValue;return <section className="panel leak"><PanelTitle kicker="Fugas de receita" title="Onde estamos a perder conversão?" right={<div className="risk"><span>Valor potencial em risco</span><strong>{eur.format(risk)}</strong><Delta a={risk} b={prev} inverse/></div>}/><div className="leak-grid"><article><i>01</i><div><span>Encomendas não pagas</span><strong>{c.unpaidOrders}</strong><small>{eur.format(c.unpaidValue)} por receber</small></div><Delta a={c.unpaidOrders} b={p.unpaidOrders} inverse/></article><article className="danger"><i>02</i><div><span>Checkouts abandonados</span><strong>{c.abandonedCheckouts}</strong><small>{eur.format(c.abandonedValue)} potencial não convertido</small></div><Delta a={c.abandonedValue} b={p.abandonedValue} inverse/></article><article className="recovered"><i>03</i><div><span>Checkouts recuperados</span><strong>{c.recoveredCheckouts}</strong><small>recuperados no período</small></div><Delta a={c.recoveredCheckouts} b={p.recoveredCheckouts}/></article></div><p className="method">O valor de checkout abandonado é potencial comercial, não perda contabilística. O dashboard cruza Shopify, GA4 e Klaviyo para diagnosticar a etapa da fuga.</p></section>}

function Trend({c}:{c:Snapshot}){const mr=Math.max(1,...c.daily.map(x=>x.revenue)),ms=Math.max(1,...c.daily.map(x=>x.metaSpend+x.googleSpend));return <section className="panel"><PanelTitle kicker="Evolução diária" title="Receita vs. investimento" right={<div className="legend"><span><i/>Receita</span><span><b/>Ads</span></div>}/><div className="chart">{c.daily.map(x=>{const spend=x.metaSpend+x.googleSpend;return <div className="day" key={x.date} title={`${eur2.format(x.revenue)} receita · ${eur2.format(spend)} Ads`}><div><i style={{height:`${Math.max(x.revenue/mr*100,x.revenue?4:0)}%`}}/><b style={{height:`${Math.max(spend/ms*100,spend?4:0)}%`}}/></div><small>{new Date(`${x.date}T12:00:00Z`).toLocaleDateString("pt-PT",{day:"2-digit",month:"short"}).replace(".","")}</small></div>})}</div></section>}

function CRM({i}:{i:IntelligenceSnapshot}){return <section className="panel"><PanelTitle kicker="Klaviyo" title="Newsletter, campanhas e automações" right={<span className="pill">atribuição Klaviyo separada da receita Shopify</span>}/><div className="crm-grid"><div><h3>Campanhas</h3><div className="table compact"><table><thead><tr><th>Campanha</th><th>Receita</th><th>Conv.</th><th>Open</th><th>Click</th><th>RPR</th></tr></thead><tbody>{i.klaviyoCampaigns.slice(0,8).map(r=><tr key={r.campaign}><td className="name">{r.campaign}<small>{r.sentAt?date(r.sentAt.slice(0,10)):""}</small></td><td>{eur.format(r.conversionValue)}</td><td>{int.format(r.conversions)}</td><td>{pct(r.openRate)}</td><td>{pct(r.clickRate)}</td><td>{eur2.format(r.revenuePerRecipient)}</td></tr>)}</tbody></table></div></div><div><h3>Flows</h3><div className="flow-list">{i.klaviyoFlows.slice(0,8).map(r=><div key={`${r.flow}-${r.message}`}><div><strong>{r.flow}</strong><small>{r.message}</small></div><span>{eur.format(r.conversionValue)}<small>{int.format(r.conversions)} conv.</small></span></div>)}</div></div></div></section>}

function Geo({i}:{i:IntelligenceSnapshot}){return <section className="panel"><PanelTitle kicker="Portugal · geografia comercial" title="Investimento, vendas e margem de progressão por distrito" right={<span className="pill">modelo interno de oportunidade</span>}/><div className="geo-note">Receita usa morada de envio Shopify; investimento usa localização reportada pelas plataformas. O ROAS geográfico é um indicador de eficiência comercial, não uma atribuição causal 1:1.</div><div className="table"><table><thead><tr><th>Distrito</th><th>Receita</th><th>Pedidos</th><th>Meta</th><th>Google</th><th>Ads total</th><th>ROAS geo</th><th>Sessões</th><th>Checkout</th><th>Compra</th><th>Conv.</th><th>Oportunidade</th></tr></thead><tbody>{i.districtRows.slice(0,20).map(r=><tr key={r.district}><td className="name">{r.district}</td><td>{eur.format(r.shopifyRevenue)}</td><td>{int.format(r.shopifyOrders)}</td><td>{eur.format(r.metaSpend)}</td><td>{eur.format(r.googleSpend)}</td><td>{eur.format(r.totalSpend)}</td><td className={r.roas!==null&&r.roas>=4?"positive":r.roas!==null&&r.roas<1.5?"negative":""}>{r.roas===null?"—":`${one.format(r.roas)}×`}</td><td>{int.format(r.sessions)}</td><td>{int.format(r.checkouts)}</td><td>{int.format(r.analyticsPurchases)}</td><td>{r.conversionRate===null?"—":pct(r.conversionRate)}</td><td><span className={`opp ${r.opportunityBand.toLowerCase().replace("é","e")}`}>{r.opportunityBand} · {r.opportunityScore}</span></td></tr>)}</tbody></table></div></section>}

function Campaigns({rows}:{rows:CampaignRow[]}){return <section className="panel"><PanelTitle kicker="Meta + Google" title="Diagnóstico de campanhas" right={<span className="pill">conversões reportadas pelas plataformas</span>}/>{rows.length?<div className="table"><table><thead><tr><th>Plataforma</th><th>Grupo</th><th>Campanha</th><th>Invest.</th><th>Conv.</th><th>Valor</th><th>ROAS</th><th>CPA</th><th>CTR</th><th>CPC</th></tr></thead><tbody>{rows.slice(0,18).map(r=><tr key={`${r.platform}-${r.group}-${r.campaign}`}><td><span className={`badge ${r.platform.toLowerCase()}`}>{r.platform}</span></td><td>{r.group}</td><td className="name">{r.campaign}</td><td>{eur2.format(r.spend)}</td><td>{one.format(r.conversions)}</td><td>{eur.format(r.conversionValue)}</td><td className={r.roas!==null&&r.roas>=4?"positive":r.roas!==null&&r.roas<2?"negative":""}>{r.roas===null?"—":`${one.format(r.roas)}×`}</td><td>{r.cpa===null?"—":eur2.format(r.cpa)}</td><td>{r.ctr===null?"—":`${one.format(r.ctr)}%`}</td><td>{r.cpc===null?"—":eur2.format(r.cpc)}</td></tr>)}</tbody></table></div>:<div className="empty">Sem dados de campanha neste período.</div>}</section>}

function Operations({c,i}:{c:Snapshot;i:IntelligenceSnapshot}){return <section className="ops-grid"><section className="panel"><PanelTitle kicker="Pagamentos" title="Mix de pagamento"/><div className="rank-list">{c.paymentMethods.map((r,idx)=><div key={r.name}><i>{String(idx+1).padStart(2,"0")}</i><span><strong>{r.name}</strong><small>{r.orders} encomendas</small></span><b>{eur.format(r.revenue)}</b></div>)}</div></section><section className="panel"><PanelTitle kicker="Operação" title="Fulfillment"/><div className="rank-list">{c.fulfillment.map((r,idx)=><div key={r.status}><i>{String(idx+1).padStart(2,"0")}</i><span><strong>{r.status}</strong><small>{eur.format(r.revenue)}</small></span><b>{r.orders}</b></div>)}</div></section><section className="panel"><PanelTitle kicker="SEO + Merchant" title="Saúde orgânica e catálogo"/><div className="mini-kpis"><div><span>Search Console clicks</span><strong>{int.format(i.seo.clicks)}</strong></div><div><span>Impressões SEO</span><strong>{int.format(i.seo.impressions)}</strong></div><div><span>Posição média</span><strong>{one.format(i.seo.position)}</strong></div><div><span>Produtos ativos</span><strong>{int.format(i.merchant.active)}</strong></div><div><span>Reprovados</span><strong>{int.format(i.merchant.disapproved)}</strong></div><div><span>Pendentes</span><strong>{int.format(i.merchant.pending)}</strong></div></div></section></section>}

function DecisionCenter({i}:{i:IntelligenceSnapshot}){return <section className="decision-grid"><section className="panel recommendation-panel"><PanelTitle kicker="Decision Center" title="Recomendações prioritárias" right={<span className="pill">geradas a partir dos dados</span>}/><div className="recommendations">{i.recommendations.length?i.recommendations.map((r,idx)=><article key={`${r.priority}-${r.title}`}><div className="rec-top"><span className={`priority ${r.priority.toLowerCase()}`}>{r.priority}</span><small>{r.area}</small></div><h3>{r.title}</h3><p>{r.rationale}</p><div><b>Ação</b><span>{r.action}</span></div><footer><b>Impacto esperado</b><span>{r.estimatedImpact}</span></footer></article>):<div className="empty">Sem recomendações automáticas críticas para este período.</div>}</div></section><section className="panel"><PanelTitle kicker="Data trust" title="Auditoria de fiabilidade"/><div className="quality-list">{i.dataQuality.map(q=><div key={q.id}><i className={q.status}/><span><strong>{q.label}</strong><small>{q.detail}</small></span></div>)}</div><p className="method">Shopify é a fonte de verdade de receita e encomendas. GA4 mede comportamento e eventos. Klaviyo, Meta e Google usam modelos de atribuição próprios e não são somados à receita principal.</p></section></section>}

export default async function Home({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const q=await searchParams,f=defaultRange(7),from=safe(typeof q.from==="string"?q.from:undefined)||f.from,to=safe(typeof q.to==="string"?q.to:undefined)||f.to,r=from<=to?{from,to}:f,pr=previousPeriod(r);
  const [snapNow,snapPrev,intelResult,pulseResult]=await Promise.allSettled([getSnapshot(r),getSnapshot(pr),getIntelligence(r),getExecutivePulse()]);
  const c=snapNow.status==="fulfilled"?snapNow.value:null,p=snapPrev.status==="fulfilled"?snapPrev.value:null,i=intelResult.status==="fulfilled"?intelResult.value:null,pulse=pulseResult.status==="fulfilled"?pulseResult.value:[];
  if(!c||!p) return <main className="fatal"><div><span>LO</span><h1>Não foi possível carregar a camada principal do dashboard.</h1><p>Verifique a ligação Windsor.ai e as variáveis de ambiente do projeto.</p></div></main>;
  return <main className="shell"><header className="topbar"><div className="brand"><span>LO</span><div><strong>Loja do Ouro</strong><small>Business Control Center · v3</small></div></div><nav><a href="#executive">Executivo</a><a href="#funnel">Funil</a><a href="#crm">CRM</a><a href="#geo">Geografia</a><a href="#media">Media</a><a href="#decisions">Decisões</a></nav><div className="top-actions"><Picker r={r}/><form method="post" action="/api/auth/logout"><button className="logout">Sair</button></form></div></header><section className="hero" id="executive"><div><span>VISÃO 360º DO NEGÓCIO</span><h1>Toda a operação, sem perder detalhe.</h1><p>{date(r.from)} — {date(r.to)} · Shopify, GA4, Klaviyo, Meta, Google Ads, Search Console e Merchant.</p></div><aside><i/><div><span>Atualizado</span><strong>{new Date(c.generatedAt).toLocaleString("pt-PT",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Lisbon"})}</strong></div></aside></section>{pulse.length>0&&<Pulse rows={pulse}/>} {c.warnings.length>0&&<div className="warning"><strong>Atenção à cobertura de dados</strong><span>{c.warnings.join(" · ")}</span></div>}<section className="kpis"><Card label="Receita paga" value={eur.format(c.revenue)} note={`${c.orders} encomendas pagas`} a={c.revenue} b={p.revenue} dark/><Card label="Encomendas" value={int.format(c.orders)} note="pagas e não canceladas" a={c.orders} b={p.orders}/><Card label="Ticket médio" value={eur2.format(c.aov)} note="receita / encomenda paga" a={c.aov} b={p.aov}/><Card label="Margem bruta" value={c.grossMarginPct===null?"—":`${one.format(c.grossMarginPct)}%`} note={`${eur.format(c.grossProfit)} contribuição`} a={c.grossProfit} b={p.grossProfit}/><Card label="Investimento total Ads" value={eur.format(c.totalSpend)} note={`Meta ${eur.format(c.metaSpend)} · Google ${eur.format(c.googleSpend)}`} a={c.totalSpend} b={p.totalSpend} inverse/><Card label="ROAS blended" value={c.blendedRoas===null?"—":`${one.format(c.blendedRoas)}×`} note="receita Shopify / Ads totais" a={c.blendedRoas||0} b={p.blendedRoas||0}/></section><div className="cols"><Spend c={c} p={p}/><Sources c={c} p={p}/></div><Financial c={c} p={p}/>{i&&<div id="funnel"><Funnel i={i}/></div>}<Leakage c={c} p={p}/><Trend c={c}/>{i&&<div id="crm"><CRM i={i}/></div>}{i&&<div id="geo"><Geo i={i}/></div>}<div id="media"><Campaigns rows={c.campaigns}/></div>{i&&<Operations c={c} i={i}/>} {i&&<div id="decisions"><DecisionCenter i={i}/></div>}<footer className="site-footer"><div><strong>Loja do Ouro · Business Control Center</strong><span>Atualização automática prevista de madrugada + leitura live quando o dashboard é aberto.</span></div><span>Receita principal: Shopify · atribuições de plataformas apresentadas separadamente.</span></footer></main>}
